const node=(tag,text,cls)=>{const n=document.createElement(tag);if(text)n.textContent=text;if(cls)n.className=cls;return n;};
const precision={point:'Точка на карте',building:'Точка внутри здания',street:'Примерное место на улице',settlement:'Центр населённого пункта'};
let serial=0;
export function addressPicker({base,near,onSelect}){
 const uid=`address-${++serial}`,root=node('div',null,'address-picker'),label=node('label','Найти адрес'),input=node('input'),hint=node('p','Например: Зеленоградск, Курортный проспект, 1','address-hint'),list=node('div',null,'address-results'),status=node('p',null,'address-status');
 input.id=uid;label.htmlFor=uid;input.type='search';input.placeholder='Город, улица, дом';input.autocomplete='off';input.maxLength=160;input.setAttribute('role','combobox');input.setAttribute('aria-autocomplete','list');input.setAttribute('aria-expanded','false');input.setAttribute('aria-controls',`${uid}-results`);input.setAttribute('aria-describedby',`${uid}-hint ${uid}-status`);hint.id=`${uid}-hint`;status.id=`${uid}-status`;status.setAttribute('role','status');list.id=`${uid}-results`;list.setAttribute('role','listbox');list.setAttribute('aria-label','Найденные адреса');list.hidden=true;root.append(label,input,hint,list,status);
 let worker,engine,revision=0,timer,closed=false,items=[],active=-1;
 const hide=()=>{list.hidden=true;input.setAttribute('aria-expanded','false');input.removeAttribute('aria-activedescendant');active=-1;};
 const choose=i=>{const r=items[i];if(!r)return;++revision;clearTimeout(timer);hide();input.value=[r.locality,r.street,r.house].filter(Boolean).join(', ')||r.name;status.textContent=`${precision[r.precision]}. Проверьте положение на карте и уточните вход.`;onSelect({...r,title:input.value});};
 const highlight=i=>{if(!items.length)return;active=(i+items.length)%items.length;[...list.children].forEach((n,j)=>n.setAttribute('aria-selected',String(active===j)));input.setAttribute('aria-activedescendant',list.children[active].id);list.children[active].scrollIntoView({block:'nearest'});};
 const display=result=>{if(closed)return;root.dataset.engine=result.engine||'';list.replaceChildren();items=result.results||[];active=-1;input.removeAttribute('aria-activedescendant');
 if(result.error){hide();status.textContent=result.error;return;}
 if(!items.length){hide();status.textContent='Такого адреса пока нет в нашей карте. Добавьте город или выберите точку вручную.';return;}
 for(const [i,r]of items.entries()){const b=node('button',null,'address-result');b.type='button';b.id=`${uid}-result-${i}`;b.setAttribute('role','option');b.setAttribute('aria-selected','false');const title=node('strong',[r.street,r.house].filter(Boolean).join(', ')||r.name),detail=node('span',[r.locality,r.name&&r.street?r.name:'',precision[r.precision]].filter(Boolean).join(' · '));b.append(title,detail);b.onclick=()=>choose(i);list.append(b);}
 list.hidden=false;input.setAttribute('aria-expanded','true');status.textContent=`Найдено: ${result.total}. Данные OpenStreetMap от ${result.snapshot_at.split('-').reverse().join('.')}. Выберите адрес; точка сохранится только после вашего подтверждения.`;
 };
 const search=async()=>{const id=++revision,query=input.value.trim();hide();items=[];if(query.length<2){status.textContent='Введите хотя бы две буквы и добавьте номер дома, если знаете.';return;}status.textContent='Ищем в карте области…';
 try{if(typeof Worker!=='undefined'){if(!worker){worker=new Worker(new URL('address-worker.mjs?v=2',base),{type:'module'});worker.onmessage=({data})=>{if(data.id===revision)display(data);};worker.onerror=()=>{worker?.terminate();worker=null;if(!closed)fallback(id,query);};}worker.postMessage({id,query,base:String(base),near:near()});}else await fallback(id,query);}catch{await fallback(id,query);}};
 const fallback=async(id,query)=>{try{if(!engine)engine=import(new URL('address-search.mjs?v=2',base)).then(m=>m.loadAddressEngine(base)).catch(e=>{engine=null;throw e;});const ready=await engine;if(!closed&&id===revision)display(ready.search(query,near()));}catch{if(!closed&&id===revision)display({error:'Адреса не загрузились. Попробуйте ещё раз или выберите точку на карте.'});}};
 input.oninput=()=>{++revision;clearTimeout(timer);hide();status.textContent='';timer=setTimeout(search,180);};
 input.onkeydown=e=>{if(e.isComposing)return;if(e.key==='ArrowDown'&&!list.hidden){e.preventDefault();highlight(active+1);}else if(e.key==='ArrowUp'&&!list.hidden){e.preventDefault();highlight(active-1);}else if(e.key==='Enter'){e.preventDefault();if(!list.hidden)choose(active<0?0:active);else search();}else if(e.key==='Escape'&&!list.hidden){e.preventDefault();e.stopPropagation();hide();}};
 return {root,input,destroy:()=>{closed=true;++revision;clearTimeout(timer);worker?.terminate();}};
}
